modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "driftward"
version = "${version}"
displayName = "Driftward"
description = "Driftward modpack mechanics, integrations and fixes"
authors = "vanuta, Sol"

[[mixins]]
config = "driftward.mixins.json"

[[dependencies.driftward]]
modId = "neoforge"
versionRange = "[21.1,)"

[[dependencies.driftward]]
modId = "betterend"
type = "optional"
ordering = "AFTER"

[[dependencies.driftward]]
modId = "wover"
type = "optional"
ordering = "AFTER"

[[dependencies.driftward]]
modId = "lmft"
