modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "driftwardfixes"
version = "${version}"
displayName = "Driftward Fixes"
description = "Driftward modpack mechanics, integrations and fixes"
authors = "vanuta, Sol"

[[mixins]]
config = "driftward-fixes.mixins.json"

[[mixins]]
config = "driftward-fixes.aeronautics.mixins.json"

[[mixins]]
config = "driftward-fixes.gameplay.mixins.json"

[[dependencies.driftwardfixes]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"
